### PR TITLE
Grammar fixes

### PR DESCRIPTION
**Pull request by littledan**
Fixing issues reported by @GeorgNeis and @WaldemarHorwat

### CODE REVIEW

**Comment by littledan** [comment]
Landing these fixes now; reviews still welcome.

**Comment by GeorgNeis** [comment]
Could you explain why `ImportedBinding` should allow `await`?

**Comment by littledan** [comment]
Passing the [Await] parameter to ImportedBinding just turns on (redundant) error checking to ban await as a variable name. It "feels right" to enable the checking here, as opposed to just relying on the broad prohibition for the Module goal.

**Comment by GeorgNeis** [comment]
I see, thanks.

**Pull request merged**
