### PR TITLE
Allow disabling top-level await in modules.

### PR DESCRIPTION
**Pull request by Ms2ger**
This is part of the solution to <https://github.com/w3c/ServiceWorker/issues/1407>.

### CODE REVIEW

**Comment by ljharb** [comment]
This seems like a relatively major conceptual change during stage 3; should tc39 get consensus on it first?

**Comment by littledan** [comment]
I see this as a layering change. I added a TLA status update to the TC39 agenda, with a link to this PR, to be unambiguous. https://github.com/tc39/agendas/pull/621

**Comment by ljharb** [comment]
A layering change is adding a hook; this is slowing hosts to refuse to parse valid Modules.

**Comment by hax** [comment]
It's reasonable for ServiceWorker to disable TLA, but it also create a case of "disabling JavaScript features in a particular context" which very unusual in our history.

And, as I understand, many developers worry about the potential risk of TLA in deep dependencies block the whole app, and want the similar constraint like what ServiceWorker did in both WebApps and Node.js Apps.

**Comment by Ms2ger** [comment]
Alternatively, we can drop this PR, and try to find a wording to impose the additional restriction directly in the ServiceWorker (or perhaps HTML) spec. I don't have a preference either way.

**Comment by ljharb** [comment]
The change forks the language into a third parse goal, wherever it lives, and i don’t think that’s appropriate for it to live outside 262. If the spec currently allows it (i hope it doesn’t) then we should change 262 so that hosts can not arbitrarily decide which syntax to parse in which goal.

**Comment by bakkot** [comment]
Is there a reason to do this with a grammar flag, rather than just having an early error for `await` expressions?

**Comment by littledan** [comment]
Thinking about this a bit more, I that ServiceWorker should actually check [[Async]] in the module, rather than making any changes to this proposal. That way, we would also cover non-JS module types.

**Comment by littledan** [comment]
Closing this PR, as it's subsumed by the cleaner approach of https://github.com/whatwg/html/pull/4352/commits/a5cdc5b04e34f1f0083380500dcdad35300ec599 (part of https://github.com/whatwg/html/pull/4352). We'll still give a status update in TC39 explaining the interaction of ServiceWorker and top-level await.

**Pull request closed without merging**
