### PR TITLE
Normative: Flush Job Queue between module imports

### PR DESCRIPTION
**Pull request by littledan**
Closes #47, #43, #48, #50

### CODE REVIEW

**Comment by littledan** [comment]
Thinking about this a bit more, I prefer this option to #49, since it's more consistent with https://www.w3.org/2001/tag/doc/promises-guide and achieves the ordering invariants that we need.

**Comment by guybedford** [comment]
Does this approach mean that in the following case:

a.js
```js
import './b.js';
```

b.js
```js
await 0;
```

execution will run completely synchronously?

**Comment by littledan** [comment]
@guybedford 

> execution will run completely synchronously?

Well, depends what you mean by "synchronously", but basically yes. Here's another example of an observable semantic difference between this PR and #49 (I imagine this kind of thing might be what you're getting at):

a.mjs
```mjs
import "./b.mjs";
import "./c.mjs";
console.log("a");
```

b.mjs
```mjs
console.log("b1");
await 0;
console.log("b2");
```

c.mjs
```mjs
console.log("c");
```

file.html
```html
<script type=module src="a.mjs"></script>
```

In this PR, the order would be b1, b2, c, a, whereas in #49, the order would be b1, c, b2, a.

> I'm wondering if it might not be possible to:

I don't understand how this would work. Ultimately, there are two *different* Promises and capabilities: the one that's used within the cycle, and the one that's exposed at the end. If overwriting the same slot is seen as messy, we could use two different ones. (I like how the spec is based on Promises, not capabilities, where possible since it feels like giving "least authority", but I don't think that's an extremely important concern here.)

**Comment by littledan** [comment]
To clarify, `async 0` will still involve a microtask queue operation, and still happen asynchronously. The semantics of the top level of a module are, in the end, just the same as an async function. It's just that we flush the microtask queue between executing modules.

**Comment by guybedford** [comment]
I'm still against this approach, and have deep concerns about its implications for JS optimizations in future. This introduces a whole new class of bugs when using tools like Rollup, and I think #47 would be a far more sensible and intuitive approach.

**Pull request merged**
